WebShop/Models/Dbo/Order.cs
namespace WebShop.Models.Dbo;

public class Order : OrderBase, IEntity
{
    public ShoppingCart ShoppingCart { get; set; }
    public int Id { get; set; }
    public DateTime Created { get; set; }
    public DateTime Modified { get; set; }
}

WebShop/Models/ViewModel/OrderViewModel.cs
namespace WebShop.Models.ViewModel;

public class OrderViewModel : OrderBase
{
    public int Id { get; set; }
    public DateTime Created { get; set; }
    public ApplicationUserViewModel? ApplicationUser { get; set; }
    public List<AddressViewModel>? Address { get; set; }
    public ShoppingCartViewModel ShoppingCart { get; set; }
}

WebShop/Controllers/AdminController.cs
namespace WebShop.Controllers;

[Authorize(Roles = Roles.Admin)]
public class AdminController : Controller
{
    private readonly ApplicationDbContext db;
    private readonly IProductService productService;
    private readonly IToDoService toDoService;
    private readonly IMapper mapper;
    
    public AdminController(IProductService productService, IMapper mapper, ApplicationDbContext db, IToDoService toDoService)
    {
        this.productService = productService;
        this.toDoService = toDoService;
        this.mapper = mapper;
        this.db = db;
    }


    /// <summary>
    /// Dashboard
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public async Task<IActionResult> Dashboard()
    {
        ViewBag.orders = db.Order.Count();
        ViewBag.ordersTotal = db.ShoppingCartItem
            .Where(x => x.ShoppingCart.ShoppingCartStatus == ShoppingCartStatus.Succeeded)
            .Sum(x => x.Price);

        List<ApplicationUser> applicationUser = db.ApplicationUser.ToList();
        ViewBag.ApplicationUser = applicationUser;

        ViewBag.Tasks = await toDoService.GetTasks(1);
        return View();
    }


    /// <summary>
    /// ProductAdministration
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public async Task<IActionResult> ProductAdministration()
    {
        var products = await productService.GetProductsAsync();
        return View(products);
    }

    /// <summary>
    /// Details Product
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [HttpGet]
    public async Task<IActionResult> DetailsProduct(int id)
    {
        var product = await productService.GetProductAsync(id);
        return (IActionResult)product;
    }



    /// <summary>
    /// Create Product
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public async Task<IActionResult> Create()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ProductBinding model)
    {
        await productService.AddProductAsync(model);
        TempData["success"] = "Product created successfully";
        return RedirectToAction("ProductAdministration");
    }

    /// <summary>
    /// Edit Product
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public async Task<IActionResult> EditProduct(int id)
    {
        var product = await productService.GetProductAsync(id);
        var model = mapper.Map<ProductUpdateBinding>(product);
        return View(product);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditProduct(ProductUpdateBinding model)
    {
        await productService.UpdateProductAsync(model);
        TempData["success"] = "Product update successfully";
        return RedirectToAction("ProductAdministration");
    }

    /// <summary>
    /// Delete Product
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public async Task<IActionResult> DeleteProduct(int id)
    {
        var product = await productService.GetProductAsync(id);
        var model = mapper.Map<ProductUpdateBinding>(product);
        return (IActionResult)product;
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteProduct(ProductUpdateBinding model)
    {
        await productService.DeleteProductAsync(model);
        TempData["success"] = "Product deleted successfully";
        return RedirectToAction("ProductAdministration");
    }





    /// <summary>
    /// Delete
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        if (this.db.Product == null) { return Problem("Entity set 'ApplicationDbContext.Product' is null."); }
        var product = await this.db.Product.FindAsync(id);
        if (product != null)
        {
            this.db.Product.Remove(product);
            TempData["success"] = "Product deleted successfully";
        }
        await this.db.SaveChangesAsync();
        return RedirectToAction(nameof(ProductAdministration));
    }

    /// <summary>
    /// AddProductCategory
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    //public async Task<IActionResult> AddProductCategory()
    //{
    //    return View();
    //}
    [HttpPost]
    public async Task<IActionResult> AddProductCategory(ProductCategoryBinding model)
    {
        await productService.AddProductCategoryAsync(model);
        TempData["success"] = "Product created successfully";
        return RedirectToAction("ProductAdministration");
    }




    /// <summary>
    /// Order
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [HttpGet]
    public async Task<IActionResult> Order(int id)
    {
        var order = await productService.GetOrderAsync(id);
        return View(order);
    }

    /// <summary>
    /// Orders
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public async Task<IActionResult> Orders()
    {
        var orders = await productService.GetOrdersAsync();
        return View(orders);
    }

    /// <summary>
    /// SuspendOrder
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [HttpGet]
    public async Task<IActionResult> SuspendOrder(int id)
    {
        var order = await productService.SuspendOrder(id);
        return RedirectToAction("Orders");
    }




    /// <summary>
    /// Change Available Status
    /// </summary>
    /// <param name="id"></param>
    /// <param name="status"></param>
    /// <returns></returns>
    public async Task<IActionResult> ChangeAvailableStatus(int id, bool status)
    {
        var discount = await productService.ChangeAvailableStatus(id, status);
        return RedirectToAction("ProductAdministration");
    }

    /// <summary>
    /// Change Discount Status
    /// </summary>
    /// <param name="id"></param>
    /// <param name="status"></param>
    /// <returns></returns>
    public async Task<IActionResult> ChangeDiscountStatus(int id, bool status)
    {
        var discount = await productService.ChangeDiscountStatus(id, status);
        return RedirectToAction("ProductAdministration");
    }
}

WebShop/Controllers/ProductImagesController.cs
using WebShop.Models.Dbo;

namespace WebShop.Controllers;

public class ProductImagesController : Controller
{
    private readonly ApplicationDbContext db;
    private readonly IProductService productService;

    public ProductImagesController(ApplicationDbContext db, IProductService productService)
    {
        this.db = db;
        this.productService = productService;
    }

    /// <summary>
    /// Get ProductImages
    /// </summary>
    /// <returns></returns>
    public async Task<IActionResult> Index()
    {
        var productImages = this.productService.GetProductImagesAsync();
        return View(await productImages);
    }

    /// <summary>
    /// Create ProductImages
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public async Task<IActionResult> Create(int id)
    {
        return View(new ProductImagesBinding { ProductId = id });
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ProductImagesBinding model)
    {
        await productService.AddProductImagesAsync(model);
        TempData["success"] = "Product Image created successfully";
        return RedirectToAction("ProductAdministration", "Admin");
    }
    
    /// <summary>
    /// Delete
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        if (this.db.ProductImages == null) { return Problem("Entity set 'ApplicationDbContext.ProductImages' is null."); }
        var productImages = await this.db.ProductImages.FindAsync(id);
        if (productImages != null)
        {
            this.db.ProductImages.Remove(productImages);
            TempData["success"] = "Image deleted successfully!";
        }
        await this.db.SaveChangesAsync();
        //return RedirectToAction(nameof(Index));
        return RedirectToAction("ProductAdministration", "Admin");
    }


    //// GET: ProductImages
    //public async Task<IActionResult> Index()
    //{
    //    return _context.ProductImages != null ?
    //                View(await _context.ProductImages.ToListAsync()) :
    //                Problem("Entity set 'ApplicationDbContext.ProductImages'  is null.");
    //}






    // GET: ProductImages/Details/5
    //public async Task<IActionResult> Details(int? id)
    //{
    //    if (id == null || _context.ProductImages == null)
    //    {
    //        return NotFound();
    //    }

    //    var productImages = await _context.ProductImages
    //        .FirstOrDefaultAsync(m => m.Id == id);
    //    if (productImages == null)
    //    {
    //        return NotFound();
    //    }

    //    return View(productImages);
    //}

    // GET: ProductImages/Create
    //public IActionResult Create()
    //{
    //    return View();
    //}

    //// POST: ProductImages/Create
    //// To protect from overposting attacks, enable the specific properties you want to bind to.
    //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    //[HttpPost]
    //[ValidateAntiForgeryToken]
    //public async Task<IActionResult> Create([Bind("Id,Created,Name,ImageUrl")] ProductImages productImages)
    //{
    //    if (ModelState.IsValid)
    //    {
    //        _context.Add(productImages);
    //        await _context.SaveChangesAsync();
    //        return RedirectToAction(nameof(Index));
    //    }
    //    return View(productImages);
    //}

    //// GET: ProductImages/Edit/5
    //public async Task<IActionResult> Edit(int? id)
    //{
    //    if (id == null || _context.ProductImages == null)
    //    {
    //        return NotFound();
    //    }

    //    var productImages = await _context.ProductImages.FindAsync(id);
    //    if (productImages == null)
    //    {
    //        return NotFound();
    //    }
    //    return View(productImages);
    //}

    // POST: ProductImages/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    //[HttpPost]
    //[ValidateAntiForgeryToken]
    //public async Task<IActionResult> Edit(int id, [Bind("Id,Created,Name,ImageUrl")] ProductImages productImages)
    //{
    //    if (id != productImages.Id)
    //    {
    //        return NotFound();
    //    }

    //    if (ModelState.IsValid)
    //    {
    //        try
    //        {
    //            _context.Update(productImages);
    //            await _context.SaveChangesAsync();
    //        }
    //        catch (DbUpdateConcurrencyException)
    //        {
    //            if (!ProductImagesExists(productImages.Id))
    //            {
    //                return NotFound();
    //            }
    //            else
    //            {
    //                throw;
    //            }
    //        }
    //        return RedirectToAction(nameof(Index));
    //    }
    //    return View(productImages);
    //}

    //// GET: ProductImages/Delete/5
    //public async Task<IActionResult> Delete(int? id)
    //{
    //    if (id == null || _context.ProductImages == null)
    //    {
    //        return NotFound();
    //    }

    //    var productImages = await _context.ProductImages
    //        .FirstOrDefaultAsync(m => m.Id == id);
    //    if (productImages == null)
    //    {
    //        return NotFound();
    //    }

    //    return View(productImages);
    //}

    //// POST: ProductImages/Delete/5
    //[HttpPost, ActionName("Delete")]
    //[ValidateAntiForgeryToken]
    //public async Task<IActionResult> DeleteConfirmed(int id)
    //{
    //    if (_context.ProductImages == null)
    //    {
    //        return Problem("Entity set 'ApplicationDbContext.ProductImages'  is null.");
    //    }
    //    var productImages = await _context.ProductImages.FindAsync(id);
    //    if (productImages != null)
    //    {
    //        _context.ProductImages.Remove(productImages);
    //    }

    //    await _context.SaveChangesAsync();
    //    return RedirectToAction(nameof(Index));
    //}

    //private bool ProductImagesExists(int id)
    //{
    //    return (_context.ProductImages?.Any(e => e.Id == id)).GetValueOrDefault();
    //}
}

WebShop/Views/Admin/Create.cshtml
@using WebShop.Services.Interface;
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model WebShop.Models.Binding.ProductBinding
@inject IProductService productService
@{
    ViewData["Title"] = "New Product";
    Layout = "_LayoutADMIN";
    var productCategory = await productService.GetProductCategorysAsync();
}

<!-- AddProduct -->

<br />
<div class="container mt-5" align="center">
    <div class="login-form"><h2>New Product</h2></div>
</div>

<form method="post" asp-action="Create" enctype="multipart/form-data">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="form-group">
                    <input asp-for="Title" type="text" class="form-control mt-4" placeholder=" Title">
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProductCategoryId" class="control-label">&nbsp; &nbsp; Choose a category</label>
                    <select name="ProductCategoryId" class="form-select" aria-label="Default select example">
                        @foreach (var item in productCategory)
                        {
                            <option value="@item.Id">@item.Title</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <input asp-for="ShortDescription" type="text" class="form-control mt-3" placeholder=" Short description">
                    <span asp-validation-for="ShortDescription" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <textarea asp-for="Description" type="text" rows="7" class="form-control mt-3" placeholder=" Description"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="Author" type="text" class="form-control mt-3" placeholder=" Author">
                    <span asp-validation-for="Author" class="text-danger"></span>
                </div>
                <fieldset name="Available" disabled>
                    <legend>
                        <label><input type=checkbox name=club onchange="form.Available.disabled = !checked">Available</label>
                    </legend>
                    <div class="form-group">
                        <input asp-for="Quantity" type="text" class="form-control mt-3" placeholder=" Quantity">
                        <span asp-validation-for="Quantity" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input asp-for="Price" type="text" class="form-control mt-3" placeholder=" Price">
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <fieldset name="discount" disabled>
                        <legend>
                            <label>
                                <input type=checkbox name=club onchange="form.discount.disabled = !checked">
                                Discount
                            </label>
                        </legend>
                        <div class="form-group">
                            <input asp-for="DiscountPrice" type="text" class="form-control mt-3" placeholder=" Discount price">
                            <span asp-validation-for="DiscountPrice" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input asp-for="StartDate" type="date" class="form-control mt-3" placeholder=" StartDate">
                            <span asp-validation-for="StartDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input asp-for="EndDate" type="date" class="form-control mt-3" placeholder=" EndDate">
                            <span asp-validation-for="EndDate" class="text-danger"></span>
                        </div>
                    </fieldset>
                </fieldset>
            </div>
            <div class="col-lg-4">
                <div class="contact-form">
                    <div class="form-group">
                        <input asp-for="Image" type="text" class="form-control mt-4" placeholder=" Image">
                    </div>
                    <div class="form-group text-center">
                        <img id="ImagePreview" class="border-info rounded mt-4" style="max-width: 350px" />
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="contact-form">
                    <div class="form-group">
                        <input asp-for="YearOfPublication" type="text" class="form-control mt-4" placeholder=" Year of publication">
                        <span asp-validation-for="YearOfPublication" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input asp-for="Publisher" type="text" class="form-control mt-3" placeholder=" Publisher">
                        <span asp-validation-for="Publisher" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input asp-for="Isbn" type="text" class="form-control mt-3" placeholder=" ISBN">
                        <span asp-validation-for="Isbn" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <select asp-for="BookCategory" class="form-control mt-3" asp-items="Html.GetEnumSelectList<BookCategory>()"></select>
                        <span asp-validation-for="BookCategory" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <select asp-for="BookBinding" class="form-control mt-3" asp-items="Html.GetEnumSelectList<BookBinding>()"></select>
                        <span asp-validation-for="BookBinding" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input asp-for="NumberOfPages" type="text" class="form-control mt-3" placeholder=" Number of pages">
                        <span asp-validation-for="NumberOfPages" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <input asp-for="Width" type="text" class="form-control mt-3" placeholder=" Width">
                                <span asp-validation-for="Width" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <input asp-for="Height" type="text" class="form-control mt-3" placeholder=" Height">
                                <span asp-validation-for="Height" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <input asp-for="Thickness" type="text" class="form-control mt-3" placeholder=" Thickness">
                                <span asp-validation-for="Thickness" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input asp-for="Weight" type="text" class="form-control mt-3" placeholder=" Weight">
                        <span asp-validation-for="Weight" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container" align="right">
        <button type="submit" class="mt-3 mb-5 primary-btn">Create</button><a asp-controller="Admin" asp-action="ProductAdministration" class="mt-3 mb-5 secondary-btn">Back</a>
    </div>
</form>

@section Scripts{
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>*@
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ImagePreview');
            output.src = $("#Image").val();
        })

        $("#Image").on("change", function () {
            var output = document.getElementById('ImagePreview');
            output.src = $(this).val();
        })
    </script>

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

WebShop/Views/Admin/ProductAdministration.cshtml
@model List<WebShop.Models.ViewModel.ProductViewModel>
@{
    ViewData["Title"] = "Product";
    Layout = "_LayoutADMIN";
    int counter = 1;
}

<!-- Product -->
<div class="d-flex align-items-center mb-3">
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="~/Admin/Dashboard">Home</a></li>
            <li class="breadcrumb-item active">Product</li>
        </ol>
        <h1 class="page-header mb-0">Product</h1>
    </div>
    <div class="ms-auto">
        <a asp-controller="Admin" asp-action="Create" class="btn btn-success btn-rounded px-4 rounded-pill"><i class="fa fa-plus fa-lg me-2 ms-n2 text-success-900"></i> Add New</a>
    </div>
</div>
<div class="mt-5 col-xl-12">
    <!-- BEGIN panel -->
    <div class="panel panel-inverse" data-sortable-id="table-basic-7">
        <div class="panel-heading">
            <h4 class="panel-title">Product <span class="badge bg-success ms-5px">PRO</span></h4>
            <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-default" data-toggle="panel-expand"><i class="fa fa-expand"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-success" data-toggle="panel-reload"><i class="fa fa-redo"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-warning" data-toggle="panel-collapse"><i class="fa fa-minus"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-danger" data-toggle="panel-remove"><i class="fa fa-times"></i></a>
            </div>
        </div>
        <!-- BEGIN panel-body -->
        <div class="panel-body">
            <!-- BEGIN table-responsive -->
            <div class="table-responsive">
                <table class="table table-hover mb-0 align-middle">
                    <thead>
                        <tr>
                            <th style="width: 2%">#</th>
                            <th style="width: 7%">Image</th>
                            <th style="width: 15%">Title</th>
                            <th>Description</th>
                            <th style="width: 15%" class="text-center">Gallery</th>
                            <th style="width: 5%" class="text-center">Available</th>
                            <th style="width: 5%" class="text-center">Quantity</th>
                            <th style="width: 5%" class="text-center">Discount</th>
                            <th>Price</th>
                            <th style="width: 11%"><a asp-controller="Admin" asp-action="Create" class="btn btn-block btn-secondary btn-sm"><i class="bi bi-plus-circle"></i> Add New</a></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            string redirectUrlAvailable = Url.Action("ChangeAvailableStatus", "Admin", new { id = item.Id, status = !item.Available });
                            string redirectUrlDiscount = Url.Action("ChangeDiscountStatus", "Admin", new { id = item.Id, status = !item.Discount });

                            <tr>
                                <td>@counter</td>
                                <td><a href="@item.Image" class="popupImg"><img src="@item.Image" width="100" /></a></td>
                                <td><b>@item.Title</b></td>
                                <td>@item.ShortDescription</td>
                                <td>
                                    <div class="container">
                                        <main role="main">
                                            <div class="row row-cols-1 row-cols-md-4 g-1">

                                                @foreach (var gallery in item.ProductImages)
                                                {
                                                    <div class="col">
                                                        <div class="card">
                                                            <img src="@gallery.ImageUrl" class="card-img-top">
                                                            @* <div class="card-img-overlay">
                                                    <button class="deleteBtn btn btn-outline-red btn-xs" type="button" data-id="@gallery.Id"><i class="bi bi-trash"></i></button>
                                                    </div>*@
                                                        </div>
                                                    </div>
                                                }
                                            </div>
                                        </main>
                                    </div>
                                </td>
                                <td class="text-center">
                                    @if (item.Available)
                                    {
                                        <input class="form-check-input" type="checkbox" onclick="RedirectToUrl('@redirectUrlAvailable')" checked>
                                    }
                                    else
                                    {
                                        <input class="form-check-input" type="checkbox" onclick="RedirectToUrl('@redirectUrlAvailable')">
                                    }
                                </td>
                                <td class="text-center">@item.Quantity</td>
                                <td class="text-center">
                                    @if (item.Discount)
                                    {
                                        <input class="form-check-input" type="checkbox" onclick="RedirectToUrl('@redirectUrlDiscount')" checked>
                                    }
                                    else
                                    {
                                        <input class="form-check-input" type="checkbox" onclick="RedirectToUrl('@redirectUrlDiscount')">
                                    }
                                </td>
                                <td>
                                    @if (item.Discount == true)
                                    {
                                        <div><b style="color:white">@item.DiscountPrice</b><sub><s> @item.Price</s></sub></div>
                                    }
                                    else
                                    {
                                        <div><b style="color:white">@item.Price</b></div>
                                    }
                                </td>
                                <td>
                                    <div class="btn-group btn-group-sm">
                                        <a asp-controller="Shop" asp-action="ItemView" asp-route-id="@item.Id" class="btn btn-secondary btn-sm"><i class="bi bi-eye"></i></a>
                                        <a asp-controller="ProductImages" asp-action="Create" asp-route-id="@item.Id" class="btn btn-secondary btn-sm"><i class="fa-solid fa-image"></i></a>
                                        <a asp-controller="Admin" asp-action="EditProduct" asp-route-id="@item.Id" class="btn btn-secondary btn-sm"><i class="bi bi-pencil-square"></i></a>
                                        <button class="deleteBtn btn btn-secondary btn-sm" type="button" data-id="@item.Id"><i class="bi bi-trash"></i></button>
                                    </div>
                                </td>
                            </tr>
                            counter++;
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@*<form id="deleteForm" asp-controller="ProductImages" asp-action="Delete"><input type="hidden" id="leaveTypeId" name="Id" /></form>*@
<form id="deleteForm" asp-controller="Admin" asp-action="Delete"><input type="hidden" id="leaveTypeId" name="Id" /></form>