WebShop/Models/Dbo/Hero.cs
namespace WebShop.Models.Dbo;

public class Hero: HeroBase, IEntity
{
    public int Id { get; set; }
    public DateTime Created { get; set; }
    public DateTime Modified { get; set; }
}

WebShop/Models/ViewModel/HeroViewModel.cs
namespace WebShop.Models.ViewModel;

public class HeroViewModel : HeroBase
{
    public int Id { get; set; }
    public DateTime Created { get; set; }
}

WebShop/Controllers/HeroController.cs
namespace WebShop.Controllers;

public class HeroController : Controller
{
    private readonly ApplicationDbContext db;
    private readonly IProductService productService;

    public HeroController(ApplicationDbContext db, IProductService productService)
    {
        this.db = db;
        this.productService = productService;
    }


    /// <summary>
    /// Hero
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var hero = await productService.GetHerosAsync();
        return View(hero);
    }

    /// <summary>
    /// Details Hero
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [HttpGet]
    public async Task<IActionResult> Details(int id)
    {
        var hero = await productService.GetHeroAsync(id);
        return View(hero);
    }
    
    /// <summary>
    /// Create Hero
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public async Task<IActionResult> Create()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(HeroBinding model)
    {
        await productService.AddHeroAsync(model);
        TempData["success"] = "Hero created successfully!";
        return RedirectToAction("Index");
    }

    /// <summary>
    /// Edit Hero
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var hero = await productService.GetHeroAsync(id);
        return View(hero);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(HeroBinding model)
    {
        await productService.UpdateHeroAsync(model);
        TempData["success"] = "Hero update successfully!";
        return RedirectToAction("Index");
    }
    
    /// <summary>
    /// Delete Hero
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        if (this.db.Hero == null) { return Problem("Entity set 'ApplicationDbContext.Hero' is null."); }
        var hero = await this.db.Hero.FindAsync(id);
        if (hero != null)
        {
            this.db.Hero.Remove(hero);
            TempData["success"] = "Hero deleted successfully!";
        }
        await this.db.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
    
    /// <summary>
    /// Change Publish Status
    /// </summary>
    /// <param name="id"></param>
    /// <param name="status"></param>
    /// <returns></returns>
    public async Task<IActionResult> ChangePublishStatus(int id, bool status)
    {
        var hero = await db.Hero.FindAsync(id);
        if (hero == null) { return null; }
        hero.Publish = status;
        await db.SaveChangesAsync();
        TempData["success"] = "Hero successfully publish!";
        return RedirectToAction("Index");
    }
}

WebShop/Views/Hero/Create.cshtml
@model WebShop.Models.Binding.HeroBinding
@{
    ViewData["Title"] = "New Hero";
    Layout = "_LayoutADMIN";
}
<!-- New Hero -->
<div class="d-flex align-items-center mb-3">
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="~/Admin/Dashboard">Home</a></li>
            <li class="breadcrumb-item"><a href="~/Hero">Hero</a></li>
            <li class="breadcrumb-item active">Create</li>
        </ol>
        <h1 class="page-header mb-0">Hero @*<small>Create</small>*@</h1>
    </div>
</div>
<div class="mt-5 col-xl-8 offset-xl-2">
    <!-- BEGIN panel -->
    <div class="panel panel-inverse" data-sortable-id="form-stuff-3">
        <!-- BEGIN panel-heading -->
        <div class="panel-heading">
            <h4 class="panel-title">Hero <span class="badge bg-success ms-1">NEW</span></h4>
            <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-default" data-toggle="panel-expand"><i class="fa fa-expand"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-success" data-toggle="panel-reload"><i class="fa fa-redo"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-warning" data-toggle="panel-collapse"><i class="fa fa-minus"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-danger" data-toggle="panel-remove"><i class="fa fa-times"></i></a>
            </div>
        </div>
        <!-- END panel-heading -->
        <!-- BEGIN panel-body -->
        <form method="post" asp-action="Create">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-floating mt-4 mb-3 mb-md-0">
                            <input asp-for="Title" type="text" class="form-control fs-15px" id="floatingInput" placeholder=" Title">
                            <label for="floatingInput" class="d-flex align-items-center fs-13px"> Title</label>
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="form-floating mt-3 mb-3 mb-md-0">
                            <input asp-for="Subtitle" type="text" class="form-control fs-15px" id="floatingInput" placeholder=" Subtitle">
                            <label for="floatingInput" class="d-flex align-items-center fs-13px"> Subtitle</label>
                            <span asp-validation-for="Subtitle" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <textarea asp-for="Description" type="text" rows="10" class="form-control mt-3" placeholder=" Description"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        </div>
                    <div class="col-lg-4">
                        <div class="contact-form">
                            <div class="form-group">
                                <input asp-for="ImageUrl" type="file" class="form-control mt-4" placeholder=" ImageUrl">
                            </div>
                            <div class="form-floating mt-3 mb-3 mb-md-0">
                                <input asp-for="ProductUrl" type="text" class="form-control fs-15px" id="floatingInput" placeholder=" ProductUrl">
                                <label for="floatingInput" class="d-flex align-items-center fs-13px"> ProductUrl</label>
                                <span asp-validation-for="ProductUrl" class="text-danger"></span>
                            </div>
                            <div class="form-floating mt-3 mb-3 mb-md-0">
                                <input asp-for="Align" type="text" class="form-control fs-15px" id="floatingInput" placeholder=" Align">
                                <label for="floatingInput" class="d-flex align-items-center fs-13px"> Align</label>
                                <span asp-validation-for="Align" class="text-danger"></span>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="form-group mt-3" align="center">
                                        <label asp-for="ColorTitle" class="form-label">Color Title</label>
                                        <input asp-for="ColorTitle" name="ColorTitle" type="color" class="form-control form-control-color" id="ColorTitle" title="Choose your color for Title">
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group mt-3" align="center">
                                        <label asp-for="ColorDescription" class="form-label">Color Description</label>
                                        <input asp-for="ColorDescription" name="ColorDescription" type="color" class="form-control form-control-color" id="ColorDescription" title="Choose your color for Description">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-floating mt-4 mb-3 mb-md-0">
                            <input asp-for="EventName" type="text" class="form-control fs-15px" id="floatingInput" placeholder=" EventName">
                            <label for="floatingInput" class="d-flex align-items-center fs-13px"> EventName</label>
                            <span asp-validation-for="EventName" class="text-danger"></span>
                        </div>
                        <div class="form-floating mt-3 mb-3 mb-md-0">
                            <input asp-for="EventText" type="text" class="form-control fs-15px" id="floatingInput" placeholder=" EventText">
                            <label for="floatingInput" class="d-flex align-items-center fs-13px"> EventText</label>
                            <span asp-validation-for="EventText" class="text-danger"></span>
                        </div>
                        <input asp-for="Publish" type="text" name="Publish" value="True" hidden>
                    </div>
                </div>
                <div align="right" class="mt-3">
                    <input type="submit" class="btn btn-primary" value="Create" /><a asp-controller="Hero" asp-action="Index" class="btn btn-default active">Back</a>
                </div>
            </div>
        </form>
    </div>
    <!-- END panel -->
</div>
<!-- END col-6 -->
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

WebShop/Views/Hero/Edit.cshtml
@model WebShop.Models.ViewModel.HeroViewModel
@{
    ViewData["Title"] = "Edit Hero";
    Layout = "_LayoutADMIN";
}
<!-- New Hero -->
<div class="d-flex align-items-center mb-3">
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="~/Admin/Dashboard">Home</a></li>
            <li class="breadcrumb-item"><a href="~/Hero">Hero</a></li>
            <li class="breadcrumb-item active">Edit</li>
        </ol>
        <h1 class="page-header mb-0">Hero @*<small>Create</small>*@</h1>
    </div>
</div>
<div class="mt-5 col-xl-8 offset-xl-2">
    <!-- BEGIN panel -->
    <div class="panel panel-inverse" data-sortable-id="form-stuff-3">
        <!-- BEGIN panel-heading -->
        <div class="panel-heading">
            <h4 class="panel-title">Hero <span class="badge bg-success ms-1">EDIT</span></h4>
            <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-default" data-toggle="panel-expand"><i class="fa fa-expand"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-success" data-toggle="panel-reload"><i class="fa fa-redo"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-warning" data-toggle="panel-collapse"><i class="fa fa-minus"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-danger" data-toggle="panel-remove"><i class="fa fa-times"></i></a>
            </div>
        </div>
        <!-- END panel-heading -->
        <!-- BEGIN panel-body -->
        <form method="post" asp-action="Edit">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="form-floating mt-4 mb-3 mb-md-0">
                            <input asp-for="Title" type="text" class="form-control fs-15px" id="floatingInput" placeholder=" Title">
                            <label for="floatingInput" class="d-flex align-items-center fs-13px"> Title</label>
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="form-floating mt-3 mb-3 mb-md-0">
                            <input asp-for="Subtitle" type="text" class="form-control fs-15px" id="floatingInput" placeholder=" Subtitle">
                            <label for="floatingInput" class="d-flex align-items-center fs-13px"> Subtitle</label>
                            <span asp-validation-for="Subtitle" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <textarea asp-for="Description" type="text" rows="10" class="form-control mt-3" placeholder=" Description"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="contact-form">
                            <div class="form-group">
                                <input asp-for="ImageUrl" type="text" class="form-control mt-4" placeholder=" ImageUrl">
                            </div>
                            <div class="form-floating mt-3 mb-3 mb-md-0">
                                <input asp-for="ProductUrl" type="text" class="form-control fs-15px" id="floatingInput" placeholder=" ProductUrl">
                                <label for="floatingInput" class="d-flex align-items-center fs-13px"> ProductUrl</label>
                                <span asp-validation-for="ProductUrl" class="text-danger"></span>
                            </div>
                            <div class="form-floating mt-3 mb-3 mb-md-0">
                                <input asp-for="Align" type="text" class="form-control fs-15px" id="floatingInput" placeholder=" Align">
                                <label for="floatingInput" class="d-flex align-items-center fs-13px"> Align</label>
                                <span asp-validation-for="Align" class="text-danger"></span>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="form-group mt-3" align="center">
                                        <label asp-for="ColorTitle" class="form-label">Color Title</label>
                                        <input asp-for="ColorTitle" name="ColorTitle" type="color" class="form-control form-control-color" id="ColorTitle" title="Choose your color for Title">
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group mt-3" align="center">
                                        <label asp-for="ColorDescription" class="form-label">Color Description</label>
                                        <input asp-for="ColorDescription" name="ColorDescription" type="color" class="form-control form-control-color" id="ColorDescription" title="Choose your color for Description">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-floating mt-4 mb-3 mb-md-0">
                            <input asp-for="EventName" type="text" class="form-control fs-15px" id="floatingInput" placeholder=" EventName">
                            <label for="floatingInput" class="d-flex align-items-center fs-13px"> EventName</label>
                            <span asp-validation-for="EventName" class="text-danger"></span>
                        </div>
                        <div class="form-floating mt-3 mb-3 mb-md-0">
                            <input asp-for="EventText" type="text" class="form-control fs-15px" id="floatingInput" placeholder=" EventText">
                            <label for="floatingInput" class="d-flex align-items-center fs-13px"> EventText</label>
                            <span asp-validation-for="EventText" class="text-danger"></span>
                        </div>
                        <input asp-for="Publish" type="text" name="Publish" value="True" hidden>
                    </div>
                </div>
                <div align="right" class="mt-3">
                    <input type="submit" class="btn btn-primary" value="Update" /><a asp-controller="Hero" asp-action="Index" class="btn btn-default active">Back</a>
                </div>
            </div>
        </form>
    </div>
    <!-- END panel -->
</div>
<!-- END col-6 -->
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }





@*@{
    ViewData["Title"] = "Edit Hero";
    Layout = "_LayoutADMIN";
}
<!-- Edit Hero -->
<br />
<div class="container mt-5" align="center">
    <div class="login-form"><h2>Edit Hero</h2></div>
</div>
<form method="post" asp-action="Edit">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="form-group">
                    <input asp-for="Title" type="text" class="form-control mt-4" placeholder=" Title">
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="Subtitle" type="text" class="form-control mt-3" placeholder=" Subtitle">
                    <span asp-validation-for="Subtitle" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <textarea asp-for="Description" type="text" rows="7" class="form-control mt-3" placeholder=" Description"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="Align" type="text" class="form-control mt-3" placeholder=" Align">
                    <span asp-validation-for="Align" class="text-danger"></span>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="contact-form">
                    <div class="form-group">
                        <input asp-for="ImageUrl" type="text" class="form-control mt-4" placeholder=" ImageUrl">
                    </div>
                    <div class="form-group text-center">
                        <img id="ImagePreview" class="border-info rounded mt-4" style="max-width: 350px" />
                    </div>
                    <div class="form-group">
                        <input asp-for="ProductUrl" type="text" class="form-control mt-3" placeholder=" ProductUrl">
                        <span asp-validation-for="ProductUrl" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group mt-3" align="center">
                                <label asp-for="ColorTitle" class="form-label">Color Title</label>
                                <input asp-for="ColorTitle" name="ColorTitle" type="color" class="form-control form-control-color" id="ColorTitle" title="Choose your color for Title">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group mt-3" align="center">
                                <label asp-for="ColorDescription" class="form-label">Color Description</label>
                                <input asp-for="ColorDescription" name="ColorDescription" type="color" class="form-control form-control-color" id="ColorDescription" title="Choose your color for Description">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="form-group">
                    <input asp-for="EventName" type="text" class="form-control mt-4" placeholder=" Event Name">
                    <span asp-validation-for="EventName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="EventText" type="text" class="form-control mt-3" placeholder=" Event Text">
                    <span asp-validation-for="EventText" class="text-danger"></span>
                </div>
                <input asp-for="Publish" type="text" name="Publish" value="@Model.Publish" hidden>
            </div>
        </div>
    </div>
    <div class="container" align="right">
        <button type="submit" class="mt-3 mb-5 primary-btn">Edit</button><a asp-controller="Hero" asp-action="Index" class="mt-3 mb-5 secondary-btn">Back</a>
    </div>
</form>

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ImagePreview');
            output.src = $("#ImageUrl").val();
        })

        $("#ImageUrl").on("change", function () {
            var output = document.getElementById('ImagePreview');
            output.src = $(this).val();
        })
    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}*@

WebShop/Views/Hero/Index.cshtml
@model IEnumerable<WebShop.Models.ViewModel.HeroViewModel>
@{
    ViewData["Title"] = "Hero";
    Layout = "_LayoutADMIN";
    int counter = 1;
}
<!-- Hero -->
<div class="d-flex align-items-center mb-3">
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="~/Admin/Dashboard">Home</a></li>
            <li class="breadcrumb-item active">Hero</li>
        </ol>
        <h1 class="page-header mb-0">Hero</h1>
    </div>
    <div class="ms-auto">
        <a asp-controller="Hero" asp-action="Create" class="btn btn-success btn-rounded px-4 rounded-pill"><i class="fa fa-plus fa-lg me-2 ms-n2 text-success-900"></i> Add New</a>
    </div>
</div>
<div class="mt-5 col-xl-12">
    <!-- BEGIN panel -->
    <div class="panel panel-inverse" data-sortable-id="table-basic-7">
        <div class="panel-heading">
            <h4 class="panel-title">Hero <span class="badge bg-success ms-5px">PRO</span></h4>
            <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-default" data-toggle="panel-expand"><i class="fa fa-expand"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-success" data-toggle="panel-reload"><i class="fa fa-redo"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-warning" data-toggle="panel-collapse"><i class="fa fa-minus"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-danger" data-toggle="panel-remove"><i class="fa fa-times"></i></a>
            </div>
        </div>
        <!-- BEGIN panel-body -->
        <div class="panel-body">
            <!-- BEGIN table-responsive -->
            <div class="table-responsive">
                <table class="table table-hover mb-0 align-middle">
                    <thead>
                    <tr>
                        <th style="width: 5%">#</th>
                        <th style="width: 5%">Publish</th>
                        <th style="width: 20%">Image</th>
                        <th style="width: 20%">Title</th>
                        <th style="width: 10%">Event Name</th>
                        <th style="width: 10%">Event Text</th>
                        <th style="width: 11%"><a asp-controller="Hero" asp-action="Create" class="btn btn-block btn-secondary btn-sm"><i class="bi bi-plus-circle"></i> &nbsp; Add New</a></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model)
                    {
                        string redirectUrlPrimary = Url.Action("ChangePublishStatus", "Hero", new { id = item.Id, status = !item.Publish });
                        <tr>
                            <td>@counter</td>
                            <td>
                                @if (item.Publish)
                                {
                                    <input class="form-check-input" type="checkbox" onclick="RedirectToUrl('@redirectUrlPrimary')" checked>
                                }
                                else
                                {
                                    <input class="form-check-input" type="checkbox" onclick="RedirectToUrl('@redirectUrlPrimary')">
                                }
                            </td>
                            <td><a href="@item.ImageUrl" class="popupImg"><img src="@item.ImageUrl" width="300" /></a></td>
                            <td>@item.Title</td>
                            <td>@item.EventName</td>
                            <td>@item.EventText</td>
                            <td>
                                <div class="btn-group btn-group-sm">
                                    <a asp-controller="Hero" asp-action="Details" asp-route-id="@item.Id" class="btn btn-secondary btn-sm"><i class="bi bi-eye"></i></a>
                                    <a asp-controller="Hero" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-secondary btn-sm"><i class="bi bi-pencil-square"></i></a>
                                    <button class="deleteBtn btn btn-secondary btn-sm" type="button" data-id="@item.Id"><i class="bi bi-trash"></i></button>
                                </div>
                            </td>
                        </tr>
                        counter++;
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<form id="deleteForm" asp-action="Delete"><input type="hidden" id="leaveTypeId" name="Id" /></form>